# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -job4jstudy@yandex.ru
    on_success: never # default: change
    on_failure: always # defa,ult: always

    env:
      global:
        - CODECOV_TOKEN="334b7659-2d14-4af9-bc27-50fbfd55da7d"